### ISSUE TITLE
Images/icons are too big, text is misaligned. Issues with help links under App

### ISSUE THREAD

**Issue by Strobey** [podlove/podlove-subscribe-button#47]
![podlove window screwed up images](https://cloud.githubusercontent.com/assets/12099861/7336876/21eb5cfa-ec55-11e4-8961-c7db8030cd3f.png)
Not sure what causes this, assuming it is some CSS thing that podlove is not overriding with a local setting.
Confirmed on multiple browsers over 2 computers and a windows 8.1 phone.
It's on wordpress with the Pinstagram theme - see here (link on bottom right) - http://drivenmedia.com.au/wp/

Also I noticed that if under "App" if  I choose gPodder, the "Visit gPodder website" under the "Try again" screen just takes me back to our site. Same with the iTunes link. (this is on windows btw - if on the win8.1 phone, it takes me to an about:blank window).
Under "Cloud" the equivalent links are OK on both PC & phone.

**Comment by Strobey** [comment]
OK I've been looking into this and found the following in the theme's css:
```css
img, video, object {
    max-width: 100%;
    height: auto!important;
}
```
The __!important__ is causing the image size issues by forcing it on _everything_. I've managed to override it by in-lining the following css in the podlove text box (note this doesn't include all the original settings, just the changed/added ones):
```css
#podlove-subscribe-popup #podlove-subscribe-panel-podcast .top-bar img,
#podlove-subscribe-popup #podlove-subscribe-panel-format .top-bar img,
#podlove-subscribe-popup #podlove-subscribe-panel-type .top-bar img,
#podlove-subscribe-popup #podlove-subscribe-panel-clients .top-bar img,
#podlove-subscribe-popup #podlove-subscribe-panel-finish .top-bar img {
    height: 26px !important;
}

#podlove-subscribe-popup #podlove-subscribe-panel-podcast img.podcast-cover {
    width: 240px !important;
}

#podlove-subscribe-popup #podlove-subscribe-panel-clients .client-list {
     line-height: 35.75px;  
}

#podlove-subscribe-popup #podlove-subscribe-panel-clients li img {
    height: 30px !important;
}
````
This also fixes the line spacing issue you can see in the screenshot, and a small annoyance with rectangular logos being shrunk unnecessarily.
You should make these changes to your app.css to fix it for everyone.
(I've never used git so not sure how to do that myself).

__Note the link issues I reported still need to be resolved so don't close the issue yet even if you make the above css changes.__ The href in the links is blank (href=""), so maybe something simple like typo in a variable name or something?
