### ISSUE TITLE
Increase cover size when there is no subtitle

### ISSUE THREAD

**Issue by benzimmer** [podlove/podlove-subscribe-button#55]
As suggested in #47 the size of the podcast's logo in the first panel should be dynamic depending on if there is a subtitle to show or not.

**Comment by Strobey** [comment]
What would also work is if it could be constrained within 150px high while being allowed to take up to the 240px maximum width available. This stops wide logos being shrunk to 150px wide (which looks poor), while still stopping tall logos from smothering the subtitle.
The following worked for me:
```css
#podlove-subscribe-popup #podlove-subscribe-panel-podcast img.podcast-cover {
    display: inline-block;
    max-height: 150px;
    max-width: 240px;
    width: auto;
    height: auto;
}
```
YMMV.
